### ISSUE TITLE
Hitcon 2015 lalala web400 task 这个writeup奇怪

### ISSUE THREAD

**Issue by leveryd** [orangetw/My-CTF-Web-Challenges#1]
> 返回的数据经过了check_image函数才能保存到磁盘中，那么这个writeup中用file:///index.php读的内容，应该不能保存到磁盘中.

> 那么是怎么可以读到index.php，或者/etc/nginx/sites-enabled/default文件呢?

```
        if ( $http_info['http_code'] == 404 ){
            alert('not found');
        } else{
            if ( check_image($data) )
                file_put_contents($DIR . $filename, $data);
        }
```

**Comment by orangetw** [comment]
Check Image 失敗會將檔案內容放置到錯誤訊息中
[lalala.php#L69](https://github.com/orangetw/My-CTF-Web-Challenges/blob/master/hitcon-ctf-2015/lalala/lalala.php#L69)
